### PR TITLE
Feed hold can now be triggered while machine is not in motion

### PR DESCRIPTION
**Pull request by kyle-kingsbury**
This is part of FabMo Engine issue https://github.com/FabMo/FabMo-Engine/issues/885 concerning feed hold within an openSBP pause. This is NOT the entire solution, but is all that can be achieved from the G2-Core side. During testing you should be able to send a feed hold within a pause, the spindle will pull up and stop spinning, then FabMo will remain in the paused state. If it is a timed pause, and the timer expires during feed hold, then FabMo will start sending gcode but G2 will not respond to it. This is how it should be and the rest will be handled from the FabMo side.

### CODE REVIEW

**Comment by RobMackie** [comment]
Kyle - does this need to be merged? Where is it with respect to PRs in FabMo-Engine?

**Comment by kyle-kingsbury** [comment]
Probably good to wait until I finish https://github.com/FabMo/FabMo-Engine/issues/885. I have the fabmo solution hard-coded and am waiting for Ted to finish his config stuff before I move forward with it.

**Comment by kyle-kingsbury** [comment]
I believe this is ready to merge. It will work in combination with https://github.com/FabMo/FabMo-Engine/pull/997. Without the fabmo changes, you should expect to transition to stat 6 from stat 3, pull up will occur, and spindle will stop.

**Comment by kyle-kingsbury** [comment]
Just did some pulse counter testing using the "make CONFIG=sbv300 USER_DEFINES=INSTRUMENT_SEGMENTS_N_MOVES" build. I was attempting to use my pcb pulse counter, but was not getting reliable readings. I used this sbp file,
so, 1,1
'Message
pause
mx, 10
pause, 5
my, 10
pause, 5
mz, 10
pause, 5
m3, 0,0,0
end
and triggered input feedhold during each pause. Aside from some minor UI discrepancies on the fabmo side, all the step counts are correct. 40000 out, 40000 back on each axis.

**Review by RobMackie — APPROVED** [review]

**Comment by RobMackie** [comment]
Used the associated branch of fabmo - ran all dev tests, plus some cuts, plus ran it with feedholds from input and feed hold from fabmo, and combinations. Also feedhold during stat:3 caused by sbp pause commands in the file. Worked as expected in all cases.  I did run into the fabmo regression of not ending a file at the user interface. had to exit browser and return to clear condition. "escape" wasn't enough. But that is a separate regression

**Pull request merged**
